require("settings")
require("plugins")

require("plugins.theme")

require("plugins.alpha")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.dap")
require("plugins.debuggers")
require("plugins.devicons")
require("plugins.gitsigns")
require("plugins.kommentary")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.sexp")
require("plugins.telescope")
require("plugins.tree")
require("plugins.treesitter")
require("plugins.whichkey")
require("plugins.wordmotion")
